import turtle
# 控制画笔的速度
turtle.speed(5)

turtle.penup()
turtle.goto(0,-270)
turtle.pencolor('red')
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(270,360)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-210)
turtle.pencolor('white')
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(210,360)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-150)
turtle.pencolor('red')
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(150,360)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-90)
turtle.pencolor('blue')
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(90,360)
turtle.end_fill()

turtle.penup()
turtle.goto(-85.59,27.81)
turtle.color('white','white')
turtle.begin_fill()
for i in range(5):
    turtle.forward(171.19)
    turtle.right(144)
turtle.end_fill()

turtle.penup()
turtle.goto(-30,-300)
turtle.pencolor('blue')
turtle.pendown()
turtle.write('爱你么么哒')
